// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: idk

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_uiclock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiclock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiclock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiclock, -1);
    lv_obj_set_y(ui_uiclock, 1);
    lv_obj_set_align(ui_uiclock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiclock, "13:27");
    lv_obj_set_style_text_color(ui_uiclock, lv_color_hex(0xEDFF3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiclock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_uiclock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_uiclock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uiclock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiclock, &ui_font_lemonMilkBI40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_distanceLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_distanceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_distanceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_distanceLabel, 56);
    lv_obj_set_y(ui_distanceLabel, 53);
    lv_obj_set_align(ui_distanceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_distanceLabel, "2.3");
    lv_obj_set_style_text_letter_space(ui_distanceLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_distanceLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_distanceLabel, &ui_font_coolvectiva30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bpmLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_bpmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bpmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bpmLabel, -61);
    lv_obj_set_y(ui_bpmLabel, 53);
    lv_obj_set_align(ui_bpmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bpmLabel, "68");
    lv_obj_set_style_text_letter_space(ui_bpmLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_bpmLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmLabel, &ui_font_coolvectiva30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spoLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_spoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spoLabel, -1);
    lv_obj_set_y(ui_spoLabel, 53);
    lv_obj_set_align(ui_spoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spoLabel, "90");
    lv_obj_set_style_text_letter_space(ui_spoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_spoLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spoLabel, &ui_font_coolvectiva30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 60);
    lv_obj_set_y(ui_Label2, 69);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "KM");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFF205), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -58);
    lv_obj_set_y(ui_Label3, 68);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BPM");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFF205), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 71);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "%");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 163);
    lv_obj_set_height(ui_Chart1, 76);
    lv_obj_set_x(ui_Chart1, -4);
    lv_obj_set_y(ui_Chart1, -73);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_BAR);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFF205),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
    lv_chart_series_t * ui_Chart1_series_3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFFFFF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_3_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_3, ui_Chart1_series_3_array);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 0, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_batteryBar = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_batteryBar, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_batteryBar, 0, 4095);
    lv_bar_set_value(ui_batteryBar, 3000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batteryBar, 62);
    lv_obj_set_height(ui_batteryBar, 10);
    lv_obj_set_x(ui_batteryBar, 0);
    lv_obj_set_y(ui_batteryBar, 89);
    lv_obj_set_align(ui_batteryBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_batteryBar, lv_color_hex(0x958A8A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_batteryBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_batteryBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_batteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_batteryBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_batteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_wifiIndicator = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wifiIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiIndicator, 0);
    lv_obj_set_y(ui_wifiIndicator, 120);
    lv_obj_set_align(ui_wifiIndicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiIndicator, "*");
    lv_obj_set_style_text_font(ui_wifiIndicator, &ui_font_coolvectiva30, LV_PART_MAIN | LV_STATE_DEFAULT);

}
