// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: idk

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -4);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Connect To Wifi\nSSID : Goweser\nPw : Goweser123");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Spinner1 = lv_spinner_create(ui_Screen2, 1000, 90);
    // lv_obj_set_width(ui_Spinner1, 284);
    // lv_obj_set_height(ui_Spinner1, 244);
    // lv_obj_set_x(ui_Spinner1, 20);
    // lv_obj_set_y(ui_Spinner1, -1);
    // lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    // lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xE9FF06), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ui_Spinner1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
